const mixedForecast = [
    {day: 1, weather: "rain"},
    {day: 2, weather: "sunny"},
    {day: 3, weather: "sunny"},
    {day: 4, weather: "clear"},
    {day: 5, weather: "rain"},
    {day: 6, weather: "snow"},
    {day: 7, weather: "misty"},
    {day: 8, weather: "sunny"},
    {day: 9, weather: "clear"},
    {day: 10, weather: "foggy"},
    {day: 11, weather: "rain"},
    {day: 12, weather: "rain"},
    {day: 13, weather: "sunny"},
    {day: 14, weather: "sunny"},
    {day: 15, weather: "clear"},
    {day: 16, weather: "foggy"},
    {day: 17, weather: "cloudy"},
    {day: 18, weather: "foggy"},
    {day: 19, weather: "rain"},
    {day: 20, weather: "clear"},
    {day: 21, weather: "sunny"},
    {day: 22, weather: "rain"},
    {day: 23, weather: "rain"},
    {day: 24, weather: "clear"},
    {day: 25, weather: "sunny"},
    {day: 26, weather: "snow"},
    {day: 27, weather: "misty"},
    {day: 28, weather: "sunny"},    
]

const noRainForecast = [
    {day: 1, weather: "sunny"},
    {day: 2, weather: "sunny"},
    {day: 3, weather: "sunny"},
    {day: 4, weather: "clear"},
    {day: 5, weather: "sunny"},
    {day: 6, weather: "snow"},
    {day: 7, weather: "misty"},
    {day: 8, weather: "sunny"},
    {day: 9, weather: "clear"},
    {day: 10, weather: "foggy"},
    {day: 11, weather: "sunny"},
    {day: 12, weather: "sunny"},
    {day: 13, weather: "sunny"},
    {day: 14, weather: "sunny"},
    {day: 15, weather: "clear"},
    {day: 16, weather: "foggy"},
    {day: 17, weather: "cloudy"},
    {day: 18, weather: "windy"},
    {day: 19, weather: "sunny"},
    {day: 20, weather: "clear"},
    {day: 21, weather: "sunny"},
    {day: 22, weather: "sunny"},
    {day: 23, weather: "sunny"},
    {day: 24, weather: "clear"},
    {day: 25, weather: "sunny"},
    {day: 26, weather: "snow"},
    {day: 27, weather: "windy"},
    {day: 28, weather: "sunny"},    
]

const oneRainForecast = [
  { day: 1, weather: "rain" },
  { day: 2, weather: "sunny" },
  { day: 3, weather: "sunny" },
  { day: 4, weather: "clear" },
  { day: 5, weather: "sunny" },
  { day: 6, weather: "snow" },
  { day: 7, weather: "misty" },
  { day: 8, weather: "sunny" },
  { day: 9, weather: "clear" },
  { day: 10, weather: "foggy" },
  { day: 11, weather: "sunny" },
  { day: 12, weather: "sunny" },
  { day: 13, weather: "sunny" },
  { day: 14, weather: "sunny" },
  { day: 15, weather: "clear" },
  { day: 16, weather: "foggy" },
  { day: 17, weather: "cloudy" },
  { day: 18, weather: "windy" },
  { day: 19, weather: "sunny" },
  { day: 20, weather: "clear" },
  { day: 21, weather: "sunny" },
  { day: 22, weather: "sunny" },
  { day: 23, weather: "sunny" },
  { day: 24, weather: "clear" },
  { day: 25, weather: "sunny" },
  { day: 26, weather: "snow" },
  { day: 27, weather: "windy" },
  { day: 28, weather: "sunny" },
];

const allRainForecast = [
  { day: 1, weather: "rain" },
  { day: 2, weather: "rain" },
  { day: 3, weather: "rain" },
  { day: 4, weather: "rain" },
  { day: 5, weather: "rain" },
  { day: 6, weather: "rain" },
  { day: 7, weather: "rain" },
  { day: 8, weather: "rain" },
  { day: 9, weather: "rain" },
  { day: 10, weather: "rain" },
  { day: 11, weather: "rain" },
  { day: 12, weather: "rain" },
  { day: 13, weather: "rain" },
  { day: 14, weather: "rain" },
  { day: 15, weather: "rain" },
  { day: 16, weather: "rain" },
  { day: 17, weather: "rain" },
  { day: 18, weather: "rain" },
  { day: 19, weather: "rain" },
  { day: 20, weather: "rain" },
  { day: 21, weather: "rain" },
  { day: 22, weather: "rain" },
  { day: 23, weather: "rain" },
  { day: 24, weather: "rain" },
  { day: 25, weather: "rain" },
  { day: 26, weather: "rain" },
  { day: 27, weather: "rain" },
  { day: 28, weather: "rain" },
];

const oneDryForecast = [
  { day: 1, weather: "sunny" },
  { day: 2, weather: "rain" },
  { day: 3, weather: "rain" },
  { day: 4, weather: "rain" },
  { day: 5, weather: "rain" },
  { day: 6, weather: "rain" },
  { day: 7, weather: "rain" },
  { day: 8, weather: "rain" },
  { day: 9, weather: "rain" },
  { day: 10, weather: "rain" },
  { day: 11, weather: "rain" },
  { day: 12, weather: "rain" },
  { day: 13, weather: "rain" },
  { day: 14, weather: "rain" },
  { day: 15, weather: "rain" },
  { day: 16, weather: "rain" },
  { day: 17, weather: "rain" },
  { day: 18, weather: "rain" },
  { day: 19, weather: "rain" },
  { day: 20, weather: "rain" },
  { day: 21, weather: "rain" },
  { day: 22, weather: "rain" },
  { day: 23, weather: "rain" },
  { day: 24, weather: "rain" },
  { day: 25, weather: "rain" },
  { day: 26, weather: "rain" },
  { day: 27, weather: "rain" },
  { day: 28, weather: "rain" },
];

module.exports = {mixedForecast, noRainForecast, oneRainForecast, allRainForecast, oneDryForecast}
